name: Release CI
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Mark as Pre-release'
        required: false
        type: boolean
      publish:
        description: 'Publish release'
        required: false
        type: boolean
        default: true
jobs:
  job_armv8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g

      - name: Add Android targets for Rust
        run: rustup target add armv7-linux-androideabi aarch64-linux-android

      - name: Build
        run: ./gradlew assembleArmv8Release

      - name: Sign APK
        id: sign_app
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: app/build/outputs/apk/armv8/release/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Delete Unsigned APK File
        run: |
          cd app/build/outputs/apk/armv8/release/
          shopt -s extglob
          rm -rf !(*-signed*)

      - name: Build Version
        run: ./gradlew getVersion

      - name: Set Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git Branch Name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/armv8/release/*.apk app/build/outputs/apk/armv8/release/SE-Extended-${{ env.version }}-ARMV8-${{ steps.version-env.outputs.sha_short }}.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SE-Extended-ARMV8-Release
          path: app/build/outputs/apk/armv8/release/*.apk

  job_armv7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g

      - name: Add Android targets for Rust
        run: rustup target add armv7-linux-androideabi aarch64-linux-android

      - name: Build
        run: ./gradlew assembleArmv7Release

      - name: Sign APK
        id: sign_app
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: app/build/outputs/apk/armv7/release/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Delete Unsigned APK file
        run: |
          cd app/build/outputs/apk/armv7/release/
          shopt -s extglob
          rm -rf !(*-signed*)

      - name: Build Version
        run: ./gradlew getVersion

      - name: Set Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git Branch Name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/armv7/release/*.apk app/build/outputs/apk/armv7/release/SE-Extended-${{ env.version }}-ARMV7-${{ steps.version-env.outputs.sha_short }}.apk
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SE-Extended-ARMV7-Release
          path: app/build/outputs/apk/armv7/release/*.apk

  job_manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew manager:assembleRelease
        
      - name: Sign APK
        id: sign_app
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: manager/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Delete Unsigned APK file
        run: |
          cd manager/build/outputs/apk/release/
          shopt -s extglob
          rm -rf !(*-signed*)

      - name: Build Version
        run: ./gradlew getVersion

      - name: Set Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git Branch Name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK File
        run: |
          mv manager/build/outputs/apk/release/*.apk manager/build/outputs/apk/release/SE-Extended-${{ env.version }}-ARMV7-${{ steps.version-env.outputs.sha_short }}.apk


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Manager
          path: manager/build/outputs/apk/release/*.apk

  job_release:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish == true }}
    needs: [job_armv8, job_armv7, job_manager]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get current build version
        id: version-env
        run: |
          ./gradlew getVersion
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: bins/
          merge-multiple: true

      - name: Publish APK
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ inputs.prerelease }}
          files: bins/*.apk
          tag_name: v${{ env.version }}
